using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ETL_Demo.Models
{
    public class InvoiceCSVData
    {
        public int Id { get; set; }
        public string CbcAmount { get; set; }
        public string CacAddress { get; set; }
        public string CacInvoicePeriod { get; set; }
        public string CacPostalSellerAddress { get; set; }
        public string CacPostalBuyerAddress { get; set; }
        public string CacPrice { get; set; }
        public string CacTaxTotal { get; set; }
        public string CbcBaseAmount { get; set; }
        public string CbcBaseQuantity { get; set; }
        public string CbcBuyerReference { get; set; }
        public string CbcSellerCompanyID { get; set; }
        public string CbcBuyerCompanyID { get; set; }
        public string CbcSellerVATID { get; set; }
        public string CbcBuyerVATID { get; set; }
        public string CbcCompanyLegalForm { get; set; }
        public string CbcDescription { get; set; }
        public string CbcDescriptionCode { get; set; }
        public string CbcDocumentCurrencyCode { get; set; }
        public string CbcSellerElectronicMail { get; set; }
        public string CbcBuyerElectronicMail { get; set; }
        public string CbcIDInvoiceNumber { get; set; }
        public string CbcPrecedingInvoicenumber { get; set; }
        public string CbcIDPaymentAccountIdentifier { get; set; }
        public string CbcIDVATcategoryCode { get; set; }
        public string CbcIDItemCountryOfOrigin { get; set; }
        public string CbcIdentificationCode { get; set; }
        public string CbcInvoiceTypeCode { get; set; }
        public string CbcIssueDate { get; set; }
        public string CbcLineExtensionAmount { get; set; }
        public string CbcSellerName { get; set; }
        public string CbcBuyerName { get; set; }
        public string CbcNameDeliverToPartyName { get; set; }
        public string CbcNote { get; set; }
        public string CbcPayableAmount { get; set; }
        public string CbcPaymentID { get; set; }
        public string CbcPercent { get; set; }
        public string CbcSellerRegnName { get; set; }
        public string CbcBuyerRegnName { get; set; }
        public string CbcTaxableAmount { get; set; }
        public string CbcTaxCurrencyCode { get; set; }
        public string CbcTaxExclusiveAmount { get; set; }
        public string CbcTaxExemptionReason { get; set; }
        public string CbcTaxInclusiveAmount { get; set; }
        public string CbcTaxPointDate { get; set; }
        public string CbcSellerTelephone { get; set; }
        public string CbcBuyerTelephone { get; set; }
        public string NamePaymentMeansText { get; set; }
        public string SchemeID { get; set; }
        public string UnitCode { get; set; }
        public string IRBMUniqueNo { get; set; }
        public string? PaymentDueDate { get; set; }
        public DateTime? paymentDueDate { get; set; }
        public string CbcPaymentCurrencyCode { get; set; }
        public string CbcBusinessActivityDesc { get; set; }
        public string CbcMsicCode { get; set; }
        public string TotalLineAmount { get; set; }
        public string TotalChangeAmount { get; set; }
        public string TotalAllowanceAmount { get; set; }
        public string TotalTaxAmount { get; set; }
        public string PayableRoundingAmount { get; set; }
        public string PrePaidAmount { get; set; }
        public string TotalAmountDue { get; set; }
        public string Mode { get; set; }
        public string EInvoiceType { get; set; }
        public int? eTemplateId { get; set; }
        public int? templateId { get; set; }
        public string Status { get; set; }
        public DateTime? EInvoiceDateTime { get; set; }
        public string? InvoiceDateTime { get; set; }
        public string invoiceValidator { get; set; }
        public string TaxOfficeSubmitter { get; set; }
        public string WorkflowStatus { get; set; }
        public string Comments { get; set; }
        public string BulkGuid { get; set; }
        public string ApprovalType { get; set; }
        public DateTime? LastDraftSaveDate { get; set; }
        public DateTime? PendingProcessingDate { get; set; }
        public DateTime? Checker1ActionDate { get; set; }
        public DateTime? Checker2ActionDate { get; set; }
        public byte[]? Checke2ActionTime { get; set; }
        public DateTime? SubmittedToIRBDate { get; set; }
        public DateTime? IRBResponseDate { get; set; }
        public DateTime? BuyerSentDate { get; set; }
        public byte[] PdfBlob { get; set; }
        public byte[] PdfXml { get; set; }
        public string Priority { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] PdfWithQRBlob { get; set; }
        public byte[] XmlWithQRBlob { get; set; }
        public byte[] JsonInvoiceBlob { get; set; }
        public byte[] JsonWithQRBlob { get; set; }
        public string CacAddress2 { get; set; }
        public string CacAddress3 { get; set; }
        public string CacAddress4 { get; set; }
        //public string CacSellerEmail { get; set; }
        public int? ReltedInvoiceId { get; set; }
        public string EInvoiceNumber { get; set; }
        public int? TaxOfficeSchedulerId { get; set; }
        public string InvoiceVersion { get; set; }
        public string CbcSellerSSTRegistrationNumber { get; set; }
        public string CbcSellerTourismTaxRegistrationNumber { get; set; }
        public string CbcSStreetName { get; set; }
        public string CbcSAdditionalStreetName1 { get; set; }
        public string CbcSAdditionalStreetName2 { get; set; }
        public string CbcSPostalZone { get; set; }
        public string CbcSCityName { get; set; }
        public string CbcSCountrySubentity { get; set; }
        public string CbcSCountryIdentificationCode { get; set; }
        public string CbcBStreetName { get; set; }
        public string CbcBAdditionalStreetName1 { get; set; }
        public string CbcBAdditionalStreetName2 { get; set; }
        public string CbcBPostalZone { get; set; }
        public string CbcBCityName { get; set; }
        public string CbcBCountrySubentity { get; set; }
        public string CbcBCountryIdentificationCode { get; set; }
        public string CbcBSSTRegistrationNumber { get; set; }
        public string CbcDStreetName { get; set; }
        public string CbcDAdditionalStreetName1 { get; set; }
        public string CbcDAdditionalStreetName2 { get; set; }
        public string CbcDPostalZone { get; set; }
        public string CbcDCityName { get; set; }
        public string CbcDCountrySubentity { get; set; }
        public string CbcDCountryIdentificationCode { get; set; }
        public string CbcShipRecipientName { get; set; }
        public string CbcShipRecipientVATID { get; set; }
        public string CbcShipRecipientCompanyID { get; set; }
        public string CbcShipRecipientStreetName { get; set; }
        public string CbcShipRecipientAdditionalStreetName1 { get; set; }
        public string CbcShipRecipientAdditionalStreetName2 { get; set; }
        public string CbcShipRecipientPostalZone { get; set; }
        public string CbcShipRecipientCityName { get; set; }
        public string CbcShipRecipientCountrySubentity { get; set; }
        public string CbcShipRecipientCountryIdentificationCode { get; set; }
        public string CbcCalculationRate { get; set; }
        public DateTime? CbcStartDate { get; set; }
        public DateTime? CbcEndDate { get; set; }
        public string CbcSCategory { get; set; }
        public string CbcSSubCategory { get; set; }
        public string CbcSBRNNumber { get; set; }
        public string CbcSNRIC { get; set; }
        public string CbcBCategory { get; set; }
        public string CbcBSubCategory { get; set; }
        public string CbcBBRNNumber { get; set; }
        public string CbcBNRIC { get; set; }
        public string CbcShipRecipientCategory { get; set; }
        public string CbcShipRecipientSubCategory { get; set; }
        public string CbcShipRecipientBRNNumber { get; set; }
        public string CbcShipRecipientNRIC { get; set; }
        public string CacPaymentTerms { get; set; }
        public DateTime? CbcPaidDate { get; set; }
        public string CbcPaidTime { get; set; }
        public string CbcPaidId { get; set; }
        public string CbcItemClassificationCodeClass { get; set; }
        public string CbcItemClassificationCodePTC { get; set; }
        public string CbcSourceInvoiceNumber { get; set; }
        public string WorkFlowOption { get; set; }
        public DateTime? RejectRequestDateTime { get; set; }
        public string RejectionStatusReason { get; set; }
        public DateTime? CancelDateTime { get; set; }
        public string CancelStatusReason { get; set; }
        public string CancelledsubmıttedID { get; set; }
        public string IRBMUniqueIdentifierNumber { get; set; }
        public string InvoiceDocumentReferenceNumber { get; set; }
        public string CbcCustomizationID { get; set; }
        public string CbcProfileID { get; set; }
        public DateTime? CbcDueDate { get; set; }
        public string CbcAccountingCost { get; set; }
        public string CbcOrderReferenceId { get; set; }
        public string CbcSalesOrderID { get; set; }
        public string CbcEndpointId { get; set; }
        public string CbcEndpointIdschemeID { get; set; }
        public string CbcPartyTaxSchemeCompanyID { get; set; }
        public string CbcPartyTaxSchemeID { get; set; }
        public string CbcPartyLegalEntityCompanyID { get; set; }
        public string CbcPartyLegalEntityCompanyLegalForm { get; set; }
        public string CbcBuyerEndpointId { get; set; }
        public string CbcBuyerEndpointIdschemeID { get; set; }
        public string CbcBuyerPartyTaxSchemeCompanyID { get; set; }
        public string CbcBuyerPartyTaxSchemeID { get; set; }
        public string CbcBuyerPartyLegalEntityCompanyID { get; set; }
        public string CbcBuyerPartyLegalEntityCompanyLegalForm { get; set; }
        public DateTime? CbcActualDeliveryDate { get; set; }
        public string CbcDeliveryLocationId { get; set; }
        public string CbcDeliveryStreetName { get; set; }
        public string CbcDeliveryAdditionalStreetName { get; set; }
        public string CbcDeliveryCityName { get; set; }
        public string CbcDeliveryPostalZone { get; set; }
        public string CbcDeliveryAddressLine { get; set; }
        public string CbcDeliveryCountryIdentificationCode { get; set; }
        public string CacDeliveryPartyName { get; set; }
        public DateTime? CbcIRBMValidationDate { get; set; }
        public string BillerId { get; set; }
        public DateTime? ValidationDate { get; set; }
        public string ValidityHours { get; set; }
        public string InvoiceDocumentReference { get; set; }
        public string QRCode { get; set; }
        public DateTime? IRBMValidationDate { get; set; }
        public DateTime? ValidityEndDateTime { get; set; }
        public DateTime? IRBMValidationTime { get; set; }
        public string RemainingHours { get; set; }
        public string SourceFileName { get; set; }
        public string SourceName { get; set; }
        public string FıleName { get; set; }
        public DateTime? DataTıme { get; set; }
        public string FolderName { get; set; }
        public string InvoıceCreatorName { get; set; }
        public string SourceInvoıceNumber { get; set; }
        public string InvoıceNumberStatus { get; set; }
        public string ProcessType { get; set; }
        public string WorkflowType { get; set; }
        public string SchedulerName { get; set; }
        public string TaskID { get; set; }
        public DateTime? CreationDateTıme { get; set; }
        public string CreatorID { get; set; }
        public string CreationNotes { get; set; }
        public DateTime? CreationSubmissionDateTime { get; set; }
        public DateTime? CreationApprovalDateTıme { get; set; }
        public int? CreationApprovalID { get; set; }
        public string CreationApprovalNotes { get; set; }
        public string CreationApprovalStatus { get; set; }
        public DateTime? VerifıcationApprovalDateTıme { get; set; }
        public int? CreationApproverlID { get; set; }
        public int? VerificationApprovalID { get; set; }
        public int? VerificationApproverlID { get; set; }
        public string VerificationApprovalNotes { get; set; }
        public int? GenerationApprovalID { get; set; }
        public int? GenerationApproverlID { get; set; }
        public string GenerationApprovalNotes { get; set; }
        public string GenerationApprovalStatus { get; set; }
        public DateTime? GenerationApprovalDateTıme { get; set; }
        public int? ValidationApprovalID { get; set; }
        public int? ValidationApproverlID { get; set; }
        public string ValidationApprovalNotes { get; set; }
        public string ValidationApprovalStatus { get; set; }
        public DateTime? ValidationApprovalDateTıme { get; set; }
        public DateTime? SubmissionDateTıme { get; set; }
        public int? SubmitterID { get; set; }
        public string SubmissionNotes { get; set; }
        public DateTime? SubmissionApprovalDateTıme { get; set; }
        public DateTime? SubmissionApprovalSubmıtDateTıme { get; set; }
        public int? SubmissionApprovalID { get; set; }
        public string SubmissionApprovalNotes { get; set; }
        public string SubmissionApprovalStatus { get; set; }
        public int? RetryCount { get; set; }
        public DateTime? ValidityEndDateTıme { get; set; }
        public string ValidityStatus { get; set; }
        public DateTime? RejectionDateTıme { get; set; }
        public string RejectionReasons { get; set; }
        public string RejectionWFCheckerID { get; set; }
        public string RejectionWFCheckerStatus { get; set; }
        public DateTime? RejectionWFCheckerSubmitDateTıme { get; set; }
        public int? RejectionWFApproverID { get; set; }
        public string RejectionWFApprovalStatus { get; set; }
        public string RejectionWFApprovalNotes { get; set; }
        public DateTime? RejectionWFApprovalSubmitDateTıme { get; set; }

        public DateTime? CancellationDateTıme { get; set; }
        public string CancellationReasons { get; set; }
        public string CancellationWFCheckerID { get; set; }
        public string CancellationWFCheckerStatus { get; set; }
        public DateTime? CancellationWFCheckerSubmıtDateTıme { get; set; }
        public int? CancellationWFApproverID { get; set; }
        public string CancellationWFApprovalStatus { get; set; }
        public string CancellationWFApprovalNotes { get; set; }
        public DateTime? CancellationWFApprovalSubmıtDateTıme { get; set; }
        public string ETLJobName { get; set; }
        public string CbcPricingCurrencyCode { get; set; }
        public string CbcCurrencyExchangeRate { get; set; }
        public string CbcFrequencyofBilling { get; set; }
        public DateTime? CbcBillingPeriodStartDate { get; set; }
        public DateTime? CbcBillingPeriodEndDate { get; set; }
        public string PaymentMode { get; set; }
        public string CbcSupplierBankAccountNumber { get; set; }
        public string CbcBillReferenceNumber { get; set; }
        public int? SourceCalculationMode { get; set; }
        public int? EtlCalculationMode { get; set; }
        public int? İnvoiceFactorycalcutionMode { get; set; }
        public string CbcTaxRate { get; set; }
        public string CbcTaxCategory { get; set; }
        public string ValidationLink { get; set; }
        public string CustomsForm19ID { get; set; }
        public string CustomsForm19DocumentType { get; set; }
        public string Incoterms { get; set; }
        public string FTADocumentType { get; set; }
        public string FTAID { get; set; }
        public string FTADocumentDesc { get; set; }
        public string SchemeAgencyName { get; set; }
        public string CustomsForm2ID { get; set; }
        public string CustomsForm2DocumentType { get; set; }
        public string OtherChargesID { get; set; }
        public string OtherChargesChargeIndicator { get; set; }
        public string OtherChargesAmount { get; set; }
        public string OtherChargesAllowanceChargeReason { get; set; }
        public int? NotificationTemplateId { get; set; }
        public int? SMSTemplateId { get; set; }
        public string OutputFormat { get; set; }
        public string InputFormat { get; set; }
        public string Notifications { get; set; }
        public DateTime? SourceDocumentDateTime { get; set; }
        public bool? SubmittedXml { get; set; }
        public bool? QRCodeImage { get; set; }
        public bool? InvoicePdf { get; set; }
        public bool? EmailInvoicePdf { get; set; }
        public string OriginalInvoiceIRBMUniqueNo { get; set; }
        public string OriginalInvoiceNumber { get; set; }
        public string ExportAuthorizationNumber { get; set; }
        public string OutputFileName { get; set; }
        public string BuyerContactPerson { get; set; }
        public string SellerContactPerson { get; set; }
        public string NetAmount { get; set; }
        public string TotalInvoiceLines { get; set; }


        //public int Id { get; set; }
        //public int InvoiceId { get; set; }
        //public string CbcIDVATCategoryCode { get; set; }
        //public string CbcIDItemCountryOfOrigin { get; set; }
        //public string CbcDescription { get; set; }
        //public string CbcDescriptionCode { get; set; }
        //public string CbcBaseAmount { get; set; }
        //public decimal? CbcAmount { get; set; }
        //public string CreatedBy { get; set; }
        //public DateTime? CreatedDate { get; set; }
        //public string UpdatedBy { get; set; }
        //public DateTime? UpdatedDate { get; set; }
        public int? LineId { get; set; }
        public decimal? CbcDiscountRate { get; set; }
        public string CbcDiscountAmount { get; set; }
        public string CbcTaxType { get; set; }
        //public string CbcTaxRate { get; set; }
        public string CbcTaxAmount { get; set; }
        public string CbcMeasure { get; set; }
        public string CbcAllowanceType { get; set; }
        public string CbcAllowanceReasonCode { get; set; }
        public string CbcAllowanceText { get; set; }
        public string CbcAllowanceBaseAmount { get; set; }
        public string CbcAllowanceMultiplierFactor { get; set; }
        public string CbcAllowanceAmount { get; set; }
        public string CbcChargeType { get; set; }
        public string CbcChargeReasonCode { get; set; }
        public string CbcChargeText { get; set; }
        public string CbcChargeBaseAmount { get; set; }
        public string CbcChargeMultiplierFactor { get; set; }
        public string CbcChargeAmount { get; set; }
        public string CbcPrice { get; set; }
        public string CbcTaxExemptionDetails { get; set; }
        public string CbcTaxExemptedAmount { get; set; }
        public string CbcTotalExcludingTax { get; set; }
        public string CbcItemClassificationCode { get; set; }
        public string CbcProductTariffClass { get; set; }
        public string CbcTaxSchemeID { get; set; }
        public string CbcTaxSchemeAgencyID { get; set; }
        public string CbcTaxSchemeAgencyCode { get; set; }
        public string CbcInvoiceLineNetAmount { get; set; }
        public string CbcNetAmount { get; set; }
        public string ProductId { get; set; }
        public string CbcItemClassificationClass { get; set; }
        public string CbcProductTariffCode { get; set; }
        public string CbcSubtotal { get; set; }
        public string CbcSSTTaxCategory { get; set; }
        //public string CbcBaseQuantity { get; set; }
        public int DocumentSubTotalId { get; set; }
        //public int InvoiceId { get; set; }
        public string TaxAmount { get; set; }
        public string CategoryTotalLines { get; set; }
        public string CategoryTaxCategory { get; set; }
        public string CategoryTaxableAmount { get; set; }
        public string CategoryTaxAmount { get; set; }
        public string CategoryTaxRate { get; set; }
        public string CategoryTaxExemptionReason { get; set; }
        public int? InvoiceLineItemId { get; set; }
        public string CategoryTaxSchemeId { get; set; }
        public string AmountExemptedFromTax { get; set; }
        public string CbcTaxSchemeAgencyId { get; set; }

        public DateTime? InvoiceDate { get; set; }
        public DateTime? InvoiceTime { get; set; }
        public string TotalFeeChargeAmount { get; set; }
        public string TotalIncludingTax { get; set; }
        public string TotalPayableAmount { get; set; }
        public string TotalDiscountValue { get; set; }
        public string InvoiceAdditionalDiscount { get; set; }
        public string InvoiceAdditionalFee { get; set; }
        public string SupplierContactPerson { get; set; }
        public string TotalNumberOfInvoiceLines { get; set; }
        public string CustomerAccount { get; set; }
        public string BuyerFaxNo { get; set; }
        public string InvoicePreparedDate { get; set; }
        public string InvoicePreparedTime { get; set; }
        public string SupplierBankAccountName { get; set; }
        public string SupplierBankSWIFTCode { get; set; }
        public string InvoiceLevelTaxSummary { get; set; }
        public string InvoiceLevelTaxBaseAmountperTaxCode { get; set; }
        public string InvoiceLevelTaxAmountperTaxCode { get; set; }
        public string InvoiceLevelTotalAmountDueperTaxCode { get; set; }
        public string TaxCategoryUNECE5153 { get; set; }
        public string TaxCategoryUNCL5305 { get; set; }
        public string LineItemTaxCode { get; set; }
        public string TaxCatCodeForTaxAmount { get; set; }
        public string FrequencyOfBilling { get; set; }
        public string BillingPeriodStartDate { get; set; }
        public string BillingPeriodEndDate { get; set; }
        public string RefNo { get;  set; }
        public string BP_CODE { get; set; }
        public string TaxRateApplicable { get; set; }
        public string AllowancePercentage { get; set; }
        public string TaxAmountPerTaxType { get; set; }
        public string CbcChargeRate { get; set; }
        public string CbcSumOfInvoiceLineNetAmount { get; set; }
        public int TotalAmount { get; set; }
        public int TotalSourceInvoiceAmount { get; set; }
        public int TotalSourceLineItems { get; set; }
       
        //public string CbcTaxSchemeAgencyCode { get; set; }



        //public string CacBuyerEmail { get; set; }
        public string UnitPrice { get; set; }
        public string CbcItemTaxCategory { get; set; }
        public string CbcItemTaxSchemeID { get; set; }
        public string CbcItemTaxSchemeAgencyID { get; set; }
        public string CbcItemTaxSchemeAgencyCode { get; set; }
        public string NettAmount { get; set; }
        public string LabNo { get; set; }
        public string MRNNo { get; set; }
        public string HVANo { get; set; }
        public string PatientName { get; set; }
        public string Register { get; set; }
        public string AccountNumber { get; set; }
        public string AccountNo { get; set; }
        public string SettlingDate { get; set; }
        public string CreditLimit { get; set; }
        public string CreditTerm { get; set; }
        public string SalesPerson { get; set; }
        public string IssuedBy { get; set; }
        public string TotalForInvoice { get; set; }
        public string ReasonforCN { get; set; }
        public string ItemCode { get; set; }
        public string TaxCode { get; set; }
        public string OriginalInvoiceDate { get; set; }
        public string ReasonForDN { get; set; }

        public List<InvoiceLineItems> InvoiceLineItems { get; set; }
        public DocTaxSubTotal DocTaxSubTotal { get; set; }
    }


    public class InvoiceData
    {
        [Key]
        public int Id { get; set; }
        public string CbcAmount { get; set; }
        public string CacAddress { get; set; }
        public string CacInvoicePeriod { get; set; }
        public string CacPostalSellerAddress { get; set; }
        public string CacPostalBuyerAddress { get; set; }
        public string CacPrice { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public DateTime? InvoiceTime { get; set; }
        public string RefNo { get; set; }
        public string CacTaxTotal { get; set; }
        public string CbcBaseAmount { get; set; }
        public string CbcBaseQuantity { get; set; }
        public string CbcBuyerReference { get; set; }
        public string CbcSellerCompanyID { get; set; }
        public string CbcBuyerCompanyID { get; set; }
        public string CbcSellerVATID { get; set; }
        public string CbcBuyerVATID { get; set; }
        public string CbcCompanyLegalForm { get; set; }
        public string CbcDescription { get; set; }  
        public string CbcDescriptionCode { get; set; }      
        public string CbcDocumentCurrencyCode { get; set; }
        public string CbcSellerElectronicMail { get; set; }
        public string CbcBuyerElectronicMail { get; set; }
        public string CbcIDInvoiceNumber { get; set; }
        public string CbcPrecedingInvoicenumber { get; set; }
        public string CbcIDPaymentAccountIdentifier { get; set; }
        public string CbcIDVATcategoryCode { get; set; }
        public string CbcIDItemCountryOfOrigin { get; set; }
        public string CbcIdentificationCode { get; set; }
        public string CbcInvoiceTypeCode { get; set; }
        public string CbcIssueDate { get; set; }
        public string CbcLineExtensionAmount { get; set; }
        public string CbcSellerName { get; set; }
        public string CbcBuyerName { get; set; }
        public string CbcNameDeliverToPartyName { get; set; }
        public string CbcNote { get; set; }
        public string CbcPayableAmount { get; set; }
        public string CbcPaymentID { get; set; }
        public string CbcPercent { get; set; }
        public string CbcSellerRegnName { get; set; }
        public string CbcBuyerRegnName { get; set; }
        public string CbcTaxableAmount { get; set; }
        public string CbcTaxCurrencyCode { get; set; }
        public string CbcTaxExclusiveAmount { get; set; }
        public string CbcTaxExemptionReason { get; set; }
        public string CbcTaxInclusiveAmount { get; set; }
        public string CbcTaxPointDate { get; set; }
        public string CbcSellerTelephone { get; set; }
        public string CbcBuyerTelephone { get; set; }
        public string NamePaymentMeansText { get; set; }
        public string SchemeID { get; set; }
        public string UnitCode { get; set; }
        public string IRBMUniqueNo { get; set; }
        public DateTime? PaymentDueDate { get; set; }
        public string CbcPaymentCurrencyCode { get; set; }
        public string CbcBusinessActivityDesc { get; set; }
        public string CbcMsicCode { get; set; }
        public string TotalLineAmount { get; set; }
        public string TotalChangeAmount { get; set; }
        public string TotalAllowanceAmount { get; set; }
        public string TotalTaxAmount { get; set; }
        public string PayableRoundingAmount { get; set; }
        public string PrePaidAmount { get; set; }
        public string TotalAmountDue { get; set; }
        public string Mode { get; set; }
        public string EInvoiceType { get; set; }
        public int? eTemplateId { get; set; }
        public int? templateId { get; set; }
        public string Status { get; set; }
        public DateTime? EInvoiceDateTime { get; set; }
        public string invoiceValidator { get; set; }
        public string TaxOfficeSubmitter { get; set; }
        public string WorkflowStatus { get; set; }
        public string Comments { get; set; }
        public string BulkGuid { get; set; }
        public string ApprovalType { get; set; }
        public DateTime? LastDraftSaveDate { get; set; }
        public DateTime? PendingProcessingDate { get; set; }
        public DateTime? Checker1ActionDate { get; set; }
        public DateTime? Checker2ActionDate { get; set; }
        public byte[]? Checke2ActionTime { get; set; }
        public DateTime? SubmittedToIRBDate { get; set; }
        public DateTime? IRBResponseDate { get; set; }
        public DateTime? BuyerSentDate { get; set; }
        public byte[] PdfBlob { get; set; }
        public byte[] PdfXml { get; set; }
        public string Priority { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] PdfWithQRBlob { get; set; }
        public byte[] XmlWithQRBlob { get; set; }
        public byte[] JsonInvoiceBlob { get; set; }
        public byte[] JsonWithQRBlob { get; set; }
        public string CacAddress2 { get; set; }
        public string CacAddress3 { get; set; }
        public string CacAddress4 { get; set; }
        public string CacSellerEmail { get; set; }
        public int? ReltedInvoiceId { get; set; }
        public string EInvoiceNumber { get; set; }
        public int? TaxOfficeSchedulerId { get; set; }
        public string InvoiceVersion { get; set; }
        public string CbcSellerSSTRegistrationNumber { get; set; }
        public string CbcSellerTourismTaxRegistrationNumber { get; set; }
        public string CbcSStreetName { get; set; }
        public string CbcSAdditionalStreetName1 { get; set; }
        public string CbcSAdditionalStreetName2 { get; set; }
        public string CbcSPostalZone { get; set; }
        public string CbcSCityName { get; set; }
        public string CbcSCountrySubentity { get; set; }
        public string CbcSCountryIdentificationCode { get; set; }
        public string CbcBStreetName { get; set; }
        public string CbcBAdditionalStreetName1 { get; set; }
        public string CbcBAdditionalStreetName2 { get; set; }
        public string CbcBPostalZone { get; set; }
        public string CbcBCityName { get; set; }
        public string CbcBCountrySubentity { get; set; }
        public string CbcBCountryIdentificationCode { get; set; }
        public string CbcBSSTRegistrationNumber { get; set; }
        public string CbcDStreetName { get; set; }
        public string CbcDAdditionalStreetName1 { get; set; }
        public string CbcDAdditionalStreetName2 { get; set; }
        public string CbcDPostalZone { get; set; }
        public string CbcDCityName { get; set; }
        public string CbcDCountrySubentity { get; set; }
        public string CbcDCountryIdentificationCode { get; set; }
        public string CbcShipRecipientName { get; set; }
        public string CbcShipRecipientVATID { get; set; }
        public string CbcShipRecipientCompanyID { get; set; }
        public string CbcShipRecipientStreetName { get; set; }
        public string CbcShipRecipientAdditionalStreetName1 { get; set; }
        public string CbcShipRecipientAdditionalStreetName2 { get; set; }
        public string CbcShipRecipientPostalZone { get; set; }
        public string CbcShipRecipientCityName { get; set; }
        public string CbcShipRecipientCountrySubentity { get; set; }
        public string CbcShipRecipientCountryIdentificationCode { get; set; }
        public string CbcCalculationRate { get; set; }
        public DateTime? CbcStartDate { get; set; }
        public DateTime? CbcEndDate { get; set; }
        public string CbcSCategory { get; set; }
        public string CbcSSubCategory { get; set; }
        public string CbcSBRNNumber { get; set; }
        public string CbcSNRIC { get; set; }
        public string CbcBCategory { get; set; }
        public string CbcBSubCategory { get; set; }
        public string CbcBBRNNumber { get; set; }
        public string CbcBNRIC { get; set; }
        public string CbcShipRecipientCategory { get; set; }
        public string CbcShipRecipientSubCategory { get; set; }
        public string CbcShipRecipientBRNNumber { get; set; }
        public string CbcShipRecipientNRIC { get; set; }
        public string CacPaymentTerms { get; set; }
        public DateTime? CbcPaidDate { get; set; }
        public string CbcPaidTime { get; set; }
        public string CbcPaidId { get; set; }
        public string CbcItemClassificationCodeClass { get; set; }
        public string CbcItemClassificationCodePTC { get; set; }
        public string CbcSourceInvoiceNumber { get; set; }
        public string WorkFlowOption { get; set; }
        public DateTime? RejectRequestDateTime { get; set; }
        public string RejectionStatusReason { get; set; }
        public DateTime? CancelDateTime { get; set; }
        public string CancelStatusReason { get; set; }
        public string CancelledsubmıttedID { get; set; }
        public string IRBMUniqueIdentifierNumber { get; set; }
        public string InvoiceDocumentReferenceNumber { get; set; }
        public string CbcCustomizationID { get; set; }
        public string CbcProfileID { get; set; }
        public DateTime? CbcDueDate { get; set; }
        public string CbcAccountingCost { get; set; }
        public string CbcOrderReferenceId { get; set; }
        public string CbcSalesOrderID { get; set; }
        public string CbcEndpointId { get; set; }
        public string CbcEndpointIdschemeID { get; set; }
        public string CbcPartyTaxSchemeCompanyID { get; set; }
        public string CbcPartyTaxSchemeID { get; set; }
        public string CbcPartyLegalEntityCompanyID { get; set; }
        public string CbcPartyLegalEntityCompanyLegalForm { get; set; }
        public string CbcBuyerEndpointId { get; set; }
        public string CbcBuyerEndpointIdschemeID { get; set; }
        public string CbcBuyerPartyTaxSchemeCompanyID { get; set; }
        public string CbcBuyerPartyTaxSchemeID { get; set; }
        public string CbcBuyerPartyLegalEntityCompanyID { get; set; }
        public string CbcBuyerPartyLegalEntityCompanyLegalForm { get; set; }
        public DateTime? CbcActualDeliveryDate { get; set; }
        public string CbcDeliveryLocationId { get; set; }
        public string CbcDeliveryStreetName { get; set; }
        public string CbcDeliveryAdditionalStreetName { get; set; }
        public string CbcDeliveryCityName { get; set; }
        public string CbcDeliveryPostalZone { get; set; }
        public string CbcDeliveryAddressLine { get; set; }
        public string CbcDeliveryCountryIdentificationCode { get; set; }
        public string CacDeliveryPartyName { get; set; }
        public DateTime? CbcIRBMValidationDate { get; set; }
        public string BillerId { get; set; }
        public DateTime? ValidationDate { get; set; }
        public string ValidityHours { get; set; }
        public string InvoiceDocumentReference { get; set; }
        public string QRCode { get; set; }
        public DateTime? IRBMValidationDate { get; set; }
        public DateTime? ValidityEndDateTime { get; set; }
        public DateTime? IRBMValidationTime { get; set; }
        public string RemainingHours { get; set; }
        public string SourceFileName { get; set; }
        public string SourceName { get; set; }
        public string FıleName { get; set; }
        public DateTime? DataTıme { get; set; }
        public string FolderName { get; set; }
        public string InvoıceCreatorName { get; set; }
        public string SourceInvoıceNumber { get; set; }
        public string InvoıceNumberStatus { get; set; }
        public string ProcessType { get; set; }
        public string WorkflowType { get; set; }
        public string SchedulerName { get; set; }
        public string TaskID { get; set; }
        public DateTime? CreationDateTıme { get; set; }
        public string CreatorID { get; set; }
        public string CreationNotes { get; set; }
        public DateTime? CreationSubmissionDateTime { get; set; }
        public DateTime? CreationApprovalDateTıme { get; set; }
        public int? CreationApprovalID { get; set; }
        public string CreationApprovalNotes { get; set; }
        public string CreationApprovalStatus { get; set; }
        public DateTime? VerifıcationApprovalDateTıme { get; set; }
        public int? CreationApproverlID { get; set; }
        public int? VerificationApprovalID { get; set; }
        public int? VerificationApproverlID { get; set; }
        public string VerificationApprovalNotes { get; set; }
        public int? GenerationApprovalID { get; set; }
        public int? GenerationApproverlID { get; set; }
        public string GenerationApprovalNotes { get; set; }
        public string GenerationApprovalStatus { get; set; }
        public DateTime? GenerationApprovalDateTıme { get; set; }
        public int? ValidationApprovalID { get; set; }
        public int? ValidationApproverlID { get; set; }
        public string ValidationApprovalNotes { get; set; }
        public string ValidationApprovalStatus { get; set; }
        public DateTime? ValidationApprovalDateTıme { get; set; }
        public DateTime? SubmissionDateTıme { get; set; }
        public int? SubmitterID { get; set; }
        public string SubmissionNotes { get; set; }
        public DateTime? SubmissionApprovalDateTıme { get; set; }
        public DateTime? SubmissionApprovalSubmıtDateTıme { get; set; }
        public int? SubmissionApprovalID { get; set; }
        public string SubmissionApprovalNotes { get; set; }
        public string SubmissionApprovalStatus { get; set; }
        public int? RetryCount { get; set; }
        public DateTime? ValidityEndDateTıme { get; set; }
        public string ValidityStatus { get; set; }
        public DateTime? RejectionDateTıme { get; set; }
        public string RejectionReasons { get; set; }
        public string RejectionWFCheckerID { get; set; }
        public string RejectionWFCheckerStatus { get; set; }
        public DateTime? RejectionWFCheckerSubmitDateTıme { get; set; }
        public int? RejectionWFApproverID { get; set; }
        public string RejectionWFApprovalStatus { get; set; }
        public string RejectionWFApprovalNotes { get; set; }
        public DateTime? RejectionWFApprovalSubmitDateTıme { get; set; }

        public DateTime? CancellationDateTıme { get; set; }
        public string CancellationReasons { get; set; }
        public string CancellationWFCheckerID { get; set; }
        public string CancellationWFCheckerStatus { get; set; }
        public DateTime? CancellationWFCheckerSubmıtDateTıme { get; set; }
        public int? CancellationWFApproverID { get; set; }
        public string CancellationWFApprovalStatus { get; set; }
        public string CancellationWFApprovalNotes { get; set; }
        public DateTime? CancellationWFApprovalSubmıtDateTıme { get; set; }
        public string ETLJobName { get; set; }
        public string CbcPricingCurrencyCode { get; set; }
        public string CbcCurrencyExchangeRate { get; set; }
        public string CbcFrequencyofBilling { get; set; }
        public DateTime? CbcBillingPeriodStartDate { get; set; }
        public DateTime? CbcBillingPeriodEndDate { get; set; }
        public string PaymentMode { get; set; }
        public string CbcSupplierBankAccountNumber { get; set; }
        public string CbcBillReferenceNumber { get; set; }
        public int? SourceCalculationMode { get; set; }
        public int? EtlCalculationMode { get; set; }
        public int? İnvoiceFactorycalcutionMode { get; set; }
        public string CbcTaxRate { get; set; }
        public string CbcTaxCategory { get; set; }
        public string ValidationLink { get; set; }
        public string CustomsForm19ID { get; set; }
        public string CustomsForm19DocumentType { get; set; }
        public string Incoterms { get; set; }
        public string FTADocumentType { get; set; }
        public string FTAID { get; set; }
        public string FTADocumentDesc { get; set; }
        public string SchemeAgencyName { get; set; }
        public string CustomsForm2ID { get; set; }
        public string CustomsForm2DocumentType { get; set; }
        public string OtherChargesID { get; set; }
        public string OtherChargesChargeIndicator { get; set; }
        public string OtherChargesAmount { get; set; }
        public string OtherChargesAllowanceChargeReason { get; set; }
        public int? NotificationTemplateId { get; set; }
        public int? SMSTemplateId { get; set; }
        public string OutputFormat { get; set; }
        public string InputFormat { get; set; }
        public string Notifications { get; set; }
        public DateTime? SourceDocumentDateTime { get; set; }
        public bool? SubmittedXml { get; set; }
        public bool? QRCodeImage { get; set; }
        public bool? InvoicePdf { get; set; }
        public bool? EmailInvoicePdf { get; set; }
        public string OriginalInvoiceIRBMUniqueNo { get; set; }
        public string OriginalInvoiceNumber { get; set; }
        public string ExportAuthorizationNumber { get; set; }
        public string OutputFileName { get; set; }
        public string BuyerContactPerson { get; set; }
        public string SellerContactPerson { get; set; }
        public string NetAmount { get; set; }
        public string TotalInvoiceLines { get; set; }
        public string TotalIncludingTax { get; set; }
        public string TotalFeeChargeAmount { get; set; }
        public string BP_CODE { get; set; }
        public string TaxCategoryUNECE5153 { get; set; }
        public string TaxCategoryUNCL5305 { get; set; }
        public string TaxRateApplicable { get; set; }
        public string CbcChargeRate { get; set; }
        public string AllowancePercentage { get; set; }
        public string CbcSumOfInvoiceLineNetAmount { get; set; }
        public string TotalPayableAmount { get; set; }
        public string TotalDiscountValue { get; set; }
        public string InvoiceAdditionalDiscount { get; set; }
        public string InvoiceAdditionalFee { get; set; }
        public string TotalAmount { get; set; } 
        public string TotalSourceInvoiceAmount { get; set; }
        public string TotalSourceLineItems { get; set; }
        public List<InvoiceLineItems> InvoiceLineItems { get; set; }
        public DocTaxSubTotal DocTaxSubTotal { get; set; }

    }
    public class InvoiceLineItems
    {
        [Key]
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public int CreditNoteId { get; set; }
        public int DebitNoteId { get; set; }
        public int RefundNoteId { get; set; }
        public int SBInvoiceId { get; set; }
        public int SBCreditNoteId { get; set; }
        public int SBRefundNoteId { get; set; }
        public int SBDebitNoteId { get; set; }
        public string CbcIDVATCategoryCode { get; set; }
        public string CbcIDItemCountryOfOrigin { get; set; }
        public string CbcDescription { get; set; }
        public string CbcDescriptionCode { get; set; }
        public string CbcBaseAmount { get; set; }
        public string? CbcAmount { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? LineId { get; set; }
        public decimal? CbcDiscountRate { get; set; }
        public string CbcDiscountAmount { get; set; }
        public string CbcTaxType { get; set; }
        public string CbcTaxRate { get; set; }
        public string CbcTaxAmount { get; set; }
        public string CbcMeasure { get; set; }
        public string CbcAllowanceType { get; set; }
        public string CbcAllowanceReasonCode { get; set; }
        public string CbcAllowanceText { get; set; }
        public string CbcAllowanceBaseAmount { get; set; }
        public string CbcAllowanceMultiplierFactor { get; set; }
        public string CbcAllowanceAmount { get; set; }
        public string CbcChargeType { get; set; }
        public string CbcChargeReasonCode { get; set; }
        public string CbcChargeText { get; set; }
        public string CbcChargeBaseAmount { get; set; }
        public string CbcChargeMultiplierFactor { get; set; }
        public string CbcChargeAmount { get; set; }
        public string CbcPrice { get; set; }
        public string CbcTaxExemptionDetails { get; set; }
        public string CbcTaxExemptedAmount { get; set; }
        public string CbcTotalExcludingTax { get; set; }
        public string CbcItemClassificationCode { get; set; }
        public string CbcProductTariffClass { get; set; }
        public string CbcTaxSchemeID { get; set; }
        public string CbcTaxSchemeAgencyID { get; set; }
        public string CbcTaxSchemeAgencyCode { get; set; }
        public string CbcInvoiceLineNetAmount { get; set; }
        public string CbcNetAmount { get; set; }
        public string ProductId { get; set; }
        public string CbcItemClassificationClass { get; set; }
        public string cbcItemClassificationCodeClass { get; set; }
        public string cbcItemClassificationCodePTC { get; set; }
        public string CbcProductTariffCode { get; set; }
        public string CbcSubtotal { get; set; }
        public string CbcSSTTaxCategory { get; set; }
        public string CbcBaseQuantity { get; set; }

        public string CbcItemTaxSchemeID { get; set; }
        public string CbcItemTaxCategory { get; set; }
        public string CbcItemTaxSchemeAgencyID { get; set; }
        public string CbcItemTaxSchemeAgencyCode { get; set; }
       
    }
    public class DocTaxSubTotal
    {
        [Key]
        public int DocumentSubTotalId { get; set; }
        public int InvoiceId { get; set; }
        public int CreditNoteId { get; set; }
        public int DebitNoteId { get; set; }
        public int RefundNoteId { get; set; }
        public int SBInvoiceId { get; set; }
        public int SBCreditNoteId { get; set; }
        public int SBDebitNoteId { get; set; }
        public int SBRefundNoteId { get; set; }
        public string TaxAmount { get; set; }
        public string CategoryTotalLines { get; set; }
        public string CategoryTaxCategory { get; set; }
        public string CategoryTaxableAmount { get; set; }
        public string CategoryTaxAmount { get; set; }
        public string CategoryTaxRate { get; set; }
        public string CategoryTaxExemptionReason { get; set; }
        public int? InvoiceLineItemId { get; set; }
        public int? CreditNoteLineItemId { get; set; }
        public int? DebitNoteLineItemId { get; set; }
        public int? RefundNoteLineItemId { get; set; }
        public int? SBInvoiceLineItemId { get; set; }
        public int? SBCreditNoteLineItemId { get; set; }
        public int? SBDebitNoteLineItemId { get; set; }
        public int? SBRefundNoteLineItemId { get; set; }
        public string CategoryTaxSchemeId { get; set; }
        public string AmountExemptedFromTax { get; set; }
        public string CbcTaxSchemeAgencyId { get; set; }
        public string CbcTaxSchemeAgencyCode { get; set; }
        public string TaxCatCodeForTaxAmount { get; set; }
        public string TaxAmountPerTaxType { get; set; }
        public string CbcTaxSchemeID { get; set; }


        //Static Field
    }

}